// ============================================================================
// Lots BI · Meta Ads — PlatformDef.
// View: public.vw_meta_ads_diario
// Colunas: data, cliente, campanha, reach, impressions, clicks, cpc, cpm, ctr,
//          frequency, spend, results, conversions, inline_link_clicks,
//          unique_clicks, link_clicks, landing_page_views, video_views,
//          post_engagements, messaging_conversations_started,
//          messaging_first_replies, page_engagements.
// Nomes dos cards = Gerenciador de Anúncios (pt-BR).
// ============================================================================

import {
  Facebook,
  DollarSign,
  MousePointerClick,
  Eye,
  Users,
  Target,
  Activity,
  Sparkles,
  Trophy,
  Link2,
  Play,
  MousePointer2,
  Heart,
  ShoppingBag,
  MessageCircle,
  MessagesSquare,
  Globe,
} from "lucide-react";
import type { PlatformDef } from "./types";
import * as f from "./formulas";

export const metaAdsDef: PlatformDef = {
  key: "meta_ads",
  label: "Meta Ads",
  icon: Facebook,
  view: "vw_meta_ads_diario",
  campaignField: "campanha",
  description:
    "As mesmas colunas do Gerenciador de Anúncios: valor gasto, resultados, conversas, cliques e visualizações, por campanha e por dia.",
  questions: [
    "Quanto eu investi no período?",
    "Quantos resultados o Gerenciador registrou?",
    "Quantas conversas no WhatsApp/Messenger começaram?",
    "Quantos cliques no link vs cliques totais?",
    "Qual foi o CTR, CPC, CPM e custo por resultado?",
    "Qual campanha teve melhor desempenho?",
  ],
  metrics: [
    {
      key: "spend",
      column: "spend",
      label: "Valor gasto",
      format: "currency",
      aggregation: { kind: "sum" },
      icon: DollarSign,
      positiveIsGood: true,
      description: "Valor gasto (spend) na Insights API — a mesma coluna do Gerenciador.",
    },
    {
      key: "results",
      column: "results",
      label: "Resultados",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Trophy,
      positiveIsGood: true,
      description:
        "Coluna Resultados do Gerenciador: o outcome da campanha (mensagem, compra, lead, clique no link, etc.).",
    },
    {
      key: "messaging_conversations_started",
      column: "messaging_conversations_started",
      label: "Conversas por mensagem iniciadas",
      short: "Conversas",
      format: "int",
      aggregation: { kind: "sum" },
      icon: MessageCircle,
      positiveIsGood: true,
      description:
        "Conversas iniciadas no WhatsApp ou Messenger (messaging_conversation_started_7d).",
    },
    {
      key: "clicks",
      column: "clicks",
      label: "Cliques (todos)",
      short: "Cliques",
      format: "int",
      aggregation: { kind: "sum" },
      icon: MousePointerClick,
      positiveIsGood: true,
      description: "Todos os cliques no anúncio, inclusive em curtidas e comentários.",
    },
    {
      key: "inline_link_clicks",
      column: "inline_link_clicks",
      label: "Cliques no link",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Link2,
      positiveIsGood: true,
      description: "Cliques no link — a métrica de tráfego que o Gerenciador destaca.",
    },
    {
      key: "unique_clicks",
      column: "unique_clicks",
      label: "Cliques únicos",
      short: "Únicos",
      format: "int",
      aggregation: { kind: "max" },
      icon: MousePointer2,
      positiveIsGood: true,
      description: "Pico diário de cliques únicos. O Gerenciador deduplica no período inteiro.",
    },
    {
      key: "impressions",
      column: "impressions",
      label: "Impressões",
      short: "Impr.",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Eye,
      positiveIsGood: true,
      description: "Quantas vezes os anúncios foram exibidos.",
    },
    {
      key: "reach",
      column: "reach",
      label: "Alcance",
      format: "int",
      aggregation: { kind: "max" },
      icon: Users,
      positiveIsGood: true,
      description: "Maior alcance diário no período (pessoas únicas; não somar dias).",
    },
    {
      key: "video_views",
      column: "video_views",
      label: "Visualizações de vídeo de 3 segundos",
      short: "Vídeo 3s",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Play,
      positiveIsGood: true,
      description: "Reproduções de pelo menos 3 segundos (ação video_view).",
    },
    {
      key: "landing_page_views",
      column: "landing_page_views",
      label: "Visualizações da página de destino",
      short: "Página de destino",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Eye,
      positiveIsGood: true,
      description: "Ação landing_page_view — a página carregou após o clique.",
    },
    {
      key: "post_engagements",
      column: "post_engagements",
      label: "Engajamento com a publicação",
      short: "Engaj. publicação",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Heart,
      positiveIsGood: true,
      description: "Curtidas, comentários, compartilhamentos e cliques na publicação.",
    },
    {
      key: "page_engagements",
      column: "page_engagements",
      label: "Engajamento com a Página",
      short: "Engaj. Página",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Globe,
      positiveIsGood: true,
      description: "Ação page_engagement no Gerenciador.",
    },
    {
      key: "messaging_first_replies",
      column: "messaging_first_replies",
      label: "Novas conexões de mensagem",
      short: "1ª resposta",
      format: "int",
      aggregation: { kind: "sum" },
      icon: MessagesSquare,
      positiveIsGood: true,
      description: "Primeira resposta da conversa (messaging_first_reply).",
    },
    {
      key: "conversions",
      column: "conversions",
      label: "Conversões",
      format: "int",
      aggregation: { kind: "sum" },
      icon: ShoppingBag,
      positiveIsGood: true,
      description:
        "Campo conversions da Insights API (pixel, API de conversões, CRM). Não substitui Resultados.",
    },
    {
      key: "link_clicks",
      column: "link_clicks",
      label: "Cliques no link (ações)",
      short: "Link (ações)",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Link2,
      positiveIsGood: true,
      description: "Ação link_click. Use Cliques no link quando o Gerenciador mostrar os dois.",
    },
  ],
  heroMetrics: ["spend", "results", "messaging_conversations_started", "clicks"],
  kpis: [
    {
      key: "ctr",
      label: "CTR",
      format: "percent",
      positiveIsGood: true,
      compute: (t) => f.ctr(t.impressions, t.clicks),
      icon: Target,
      description: "Cliques (todos) ÷ impressões × 100.",
    },
    {
      key: "ctr_link",
      label: "CTR do link",
      format: "percent",
      positiveIsGood: true,
      compute: (t) => f.ctr(t.impressions, t.inline_link_clicks),
      icon: Target,
      description: "Cliques no link ÷ impressões × 100.",
    },
    {
      key: "cpc",
      label: "CPC",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpc(t.spend, t.clicks),
      icon: Activity,
      description: "Valor gasto ÷ cliques (todos).",
    },
    {
      key: "cpc_link",
      label: "CPC do link",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpc(t.spend, t.inline_link_clicks),
      icon: Activity,
      description: "Valor gasto ÷ cliques no link.",
    },
    {
      key: "cpm",
      label: "CPM",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpm(t.spend, t.impressions),
      icon: Sparkles,
      description: "Valor gasto ÷ impressões × 1000.",
    },
    {
      key: "frequency",
      label: "Frequência",
      format: "decimal",
      positiveIsGood: true,
      compute: (t) => f.frequency(t.impressions, t.reach),
      description: "Impressões ÷ alcance do período.",
    },
    {
      key: "cpa",
      label: "Custo por resultado",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpa(t.spend, t.results),
      icon: Activity,
      description: "Valor gasto ÷ resultados.",
    },
    {
      key: "cpa_conv",
      label: "Custo por conversão",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpa(t.spend, t.conversions),
      icon: Activity,
      description: "Valor gasto ÷ conversões.",
    },
  ],
  charts: [
    {
      key: "evolucao-investimento",
      kind: "area",
      title: "Valor gasto",
      description: "Gasto diário no período.",
      yMetric: "spend",
      series: [{ metric: "spend", label: "Valor gasto", tone: "primary" }],
      height: 260,
    },
    {
      key: "evolucao-alcance",
      kind: "area",
      title: "Alcance e impressões",
      description: "Pessoas únicas e impressões por dia.",
      yMetric: "impressions",
      series: [
        { metric: "reach", label: "Alcance", tone: "secondary" },
        { metric: "impressions", label: "Impressões", tone: "primary" },
      ],
      height: 240,
    },
    {
      key: "evolucao-resultados",
      kind: "area",
      title: "Resultados e conversas",
      description: "Resultados do Gerenciador e conversas por mensagem iniciadas.",
      yMetric: "results",
      series: [
        { metric: "results", label: "Resultados", tone: "success" },
        {
          metric: "messaging_conversations_started",
          label: "Conversas por mensagem iniciadas",
          tone: "primary",
        },
      ],
      height: 240,
    },
    {
      key: "evolucao-cliques",
      kind: "area",
      title: "Cliques",
      description: "Cliques no link e cliques totais por dia.",
      yMetric: "clicks",
      series: [
        { metric: "inline_link_clicks", label: "Cliques no link", tone: "primary" },
        { metric: "clicks", label: "Cliques (todos)", tone: "secondary" },
      ],
      height: 240,
    },
  ],
};
