// ============================================================================
// Lots BI · Meta Ads — PlatformDef.
// View: public.vw_meta_ads_diario
// Colunas: data, cliente, campanha, reach, impressions, clicks, cpc, cpm, ctr,
//          frequency, spend, results, conversions, inline_link_clicks,
//          unique_clicks, link_clicks, landing_page_views, video_views,
//          post_engagements.
// ============================================================================

import {
  Facebook,
  DollarSign,
  MousePointerClick,
  Eye,
  Users,
  Target,
  Activity,
  Sparkles,
  Trophy,
  Link2,
  Play,
  MousePointer2,
  Heart,
  ShoppingBag,
} from "lucide-react";
import type { PlatformDef } from "./types";
import * as f from "./formulas";

export const metaAdsDef: PlatformDef = {
  key: "meta_ads",
  label: "Meta Ads",
  icon: Facebook,
  view: "vw_meta_ads_diario",
  campaignField: "campanha",
  description:
    "Performance da conta Meta Ads a partir da Marketing Insights API — investimento, resultados, cliques e visualizações por campanha. Números de entrega alinham com o Gerenciador; resultados/conversões podem diferir pela janela de atribuição da conta.",
  questions: [
    "Quanto eu investi no período?",
    "Quantos resultados e conversões as campanhas geraram?",
    "Quantos cliques no link vs cliques totais?",
    "Quantas pessoas únicas viram os anúncios (visualizadores)?",
    "Quantas impressões e visualizações de vídeo houve?",
    "Qual foi o CTR, CPC, CPM e custo por resultado?",
    "Qual campanha teve melhor desempenho?",
    "Como tudo evoluiu vs o período anterior?",
  ],
  metrics: [
    {
      key: "spend",
      column: "spend",
      label: "Investimento",
      format: "currency",
      aggregation: { kind: "sum" },
      icon: DollarSign,
      positiveIsGood: true,
      description: "Valor gasto declarado pela Marketing Insights API (spend).",
    },
    {
      key: "results",
      column: "results",
      label: "Resultados",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Trophy,
      positiveIsGood: true,
      description:
        "Resultado primário da campanha no dia (compra, lead, conversa, clique no link, etc.) — equivalente à coluna Resultados do Gerenciador.",
    },
    {
      key: "conversions",
      column: "conversions",
      label: "Conversões",
      format: "int",
      aggregation: { kind: "sum" },
      icon: ShoppingBag,
      positiveIsGood: true,
      description:
        "Campo conversions da Insights API (pixel, API de conversões, CRM). Pode ser menor que Resultados quando o objetivo não é conversão.",
    },
    {
      key: "clicks",
      column: "clicks",
      label: "Cliques (todos)",
      short: "Cliques",
      format: "int",
      aggregation: { kind: "sum" },
      icon: MousePointerClick,
      positiveIsGood: true,
      description:
        "Todos os cliques no anúncio (incluindo curtidas, comentários e outros). No Gerenciador, “Cliques no link” é outra métrica.",
    },
    {
      key: "inline_link_clicks",
      column: "inline_link_clicks",
      label: "Cliques no link",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Link2,
      positiveIsGood: true,
      description:
        "inline_link_clicks — o que o Gerenciador chama de Cliques no link. A API usa janela fixa de 1 dia de clique; se o campo não vier, usamos a ação link_click.",
    },
    {
      key: "unique_clicks",
      column: "unique_clicks",
      label: "Cliques únicos (pico)",
      short: "Únicos",
      format: "int",
      aggregation: { kind: "max" },
      icon: MousePointer2,
      positiveIsGood: true,
      description:
        "Maior unique_clicks diário no período. O Gerenciador deduplica pessoas no intervalo inteiro — somar dias inflaria o número.",
    },
    {
      key: "impressions",
      column: "impressions",
      label: "Impressões",
      short: "Impr.",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Eye,
      positiveIsGood: true,
      description: "Quantas vezes os anúncios foram exibidos (visualizações da veiculação).",
    },
    {
      key: "reach",
      column: "reach",
      label: "Alcance",
      format: "int",
      aggregation: { kind: "max" },
      icon: Users,
      positiveIsGood: true,
      description:
        "Visualizadores: maior alcance diário no período (pessoas únicas; não somar dias).",
    },
    {
      key: "video_views",
      column: "video_views",
      label: "Visualizações de vídeo",
      short: "Vídeo",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Play,
      positiveIsGood: true,
      description:
        "Ação video_view: reproduções de pelo menos 3 segundos. Não é o mesmo que impressões nem que ThruPlay.",
    },
    {
      key: "landing_page_views",
      column: "landing_page_views",
      label: "Visualizações da página",
      short: "LPV",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Eye,
      positiveIsGood: true,
      description: "Ação landing_page_view (página de destino carregada após o clique).",
    },
    {
      key: "post_engagements",
      column: "post_engagements",
      label: "Engajamentos no post",
      short: "Engaj.",
      format: "int",
      aggregation: { kind: "sum" },
      icon: Heart,
      positiveIsGood: true,
      description: "Ação post_engagement (curtidas, comentários, compartilhamentos e cliques).",
    },
  ],
  heroMetrics: ["spend", "results", "conversions", "clicks"],
  kpis: [
    {
      key: "ctr",
      label: "CTR",
      format: "percent",
      positiveIsGood: true,
      compute: (t) => f.ctr(t.impressions, t.clicks),
      icon: Target,
      description: "Cliques (todos) ÷ impressões × 100.",
    },
    {
      key: "ctr_link",
      label: "CTR de link",
      format: "percent",
      positiveIsGood: true,
      compute: (t) => f.ctr(t.impressions, t.inline_link_clicks),
      icon: Target,
      description: "Cliques no link ÷ impressões × 100 — o CTR que o Gerenciador destaca em tráfego.",
    },
    {
      key: "cpc",
      label: "CPC médio",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpc(t.spend, t.clicks),
      icon: Activity,
      description: "Investimento ÷ cliques (todos).",
    },
    {
      key: "cpc_link",
      label: "CPC de link",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpc(t.spend, t.inline_link_clicks),
      icon: Activity,
      description: "Investimento ÷ cliques no link.",
    },
    {
      key: "cpm",
      label: "CPM médio",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpm(t.spend, t.impressions),
      icon: Sparkles,
      description: "Investimento ÷ impressões × 1000.",
    },
    {
      key: "frequency",
      label: "Frequência",
      format: "decimal",
      positiveIsGood: true,
      compute: (t) => f.frequency(t.impressions, t.reach),
      description: "Impressões ÷ alcance do período (vezes que cada visualizador viu, em média).",
    },
    {
      key: "cpa",
      label: "Custo por resultado",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpa(t.spend, t.results),
      icon: Activity,
      description: "Investimento ÷ resultados.",
    },
    {
      key: "cpa_conv",
      label: "Custo por conversão",
      format: "currency",
      positiveIsGood: false,
      compute: (t) => f.cpa(t.spend, t.conversions),
      icon: Activity,
      description: "Investimento ÷ conversões.",
    },
  ],
  charts: [
    {
      key: "evolucao-investimento",
      kind: "area",
      title: "Evolução do investimento",
      description: "Gasto diário consolidado no período.",
      yMetric: "spend",
      series: [{ metric: "spend", label: "Investimento", tone: "primary" }],
      height: 260,
    },
    {
      key: "evolucao-alcance",
      kind: "area",
      title: "Visualizadores e impressões",
      description: "Alcance (pessoas únicas) e impressões servidas por dia.",
      yMetric: "impressions",
      series: [
        { metric: "reach", label: "Alcance (visualizadores)", tone: "secondary" },
        { metric: "impressions", label: "Impressões", tone: "primary" },
      ],
      height: 240,
    },
    {
      key: "evolucao-cliques",
      kind: "area",
      title: "Cliques e conversões",
      description: "Cliques no link, cliques totais e conversões por dia.",
      yMetric: "clicks",
      series: [
        { metric: "inline_link_clicks", label: "Cliques no link", tone: "primary" },
        { metric: "clicks", label: "Cliques (todos)", tone: "secondary" },
        { metric: "conversions", label: "Conversões", tone: "success" },
      ],
      height: 240,
    },
    {
      key: "evolucao-resultados",
      kind: "area",
      title: "Resultados e visualizações",
      description: "Resultado primário, visualizações de vídeo e páginas de destino.",
      yMetric: "results",
      series: [
        { metric: "results", label: "Resultados", tone: "success" },
        { metric: "video_views", label: "Visualizações de vídeo", tone: "primary" },
        { metric: "landing_page_views", label: "Página de destino", tone: "secondary" },
      ],
      height: 240,
    },
  ],
};
